<a href="https://colab.research.google.com/github/ChimSovann/Machine-Learning/blob/main/Unit2_Regression_Simple%26Multiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#lib
import sklearn
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt #graph
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.metrics as metrics

In [2]:
#dataset
from google.colab import files
upload = files.upload()

Saving MY2022 Fuel Consumption Ratings.csv to MY2022 Fuel Consumption Ratings.csv


In [3]:
dataset = pd.read_csv('MY2022 Fuel Consumption Ratings.csv')
dataset.head(5)

Model Year   Make              Model Vehicle Class  Engine Size(L)  \
0        2022  Acura                ILX       Compact             2.4   
1        2022  Acura         MDX SH-AWD    SUV: Small             3.5   
2        2022  Acura         RDX SH-AWD    SUV: Small             2.0   
3        2022  Acura  RDX SH-AWD A-SPEC    SUV: Small             2.0   
4        2022  Acura         TLX SH-AWD       Compact             2.0   

   Cylinders Transmission Fuel Type  Fuel Consumption (City (L/100 km)  \
0          4          AM8         Z                                9.9   
1          6         AS10         Z                               12.6   
2          4         AS10         Z                               11.0   
3          4         AS10         Z                               11.3   
4          4         AS10         Z                               11.2   

   Fuel Consumption(Hwy (L/100 km))  Fuel Consumption(Comb (L/100 km))  \
0                               7.0                                8.6   
1                               9.4                               11.2   
2                               8.6                                9.9   
3                               9.1                               10.3   
4                               8.0                                9.8   

   Fuel Consumption(Comb (mpg))  CO2 Emissions(g/km)  CO2 Rating  Smog Rating  
0                            33                  200           6            3  
1                            25                  263           4            5  
2                            29                  232           5            6  
3                            27                  242           5            6  
4                            29                  230           5            7

In [4]:
#linear - dataset is clean and tidy (****)

In [5]:
#select the variables(x,y)

x_variable = ['Fuel Consumption(Hwy (L/100 km))']
y_variable = ['CO2 Emissions(g/km)']

#reshape variable
x = dataset[x_variable].values.reshape(-1,1) #1st value -1, next value is the length of x_variable
y = dataset[y_variable].values.reshape(-1,1) #1st value -1, next value is the length of y_variable
print(x.shape)
print(y.shape)
#(or)
z = np.array(dataset[x_variable]).reshape(-1,1)
w = np.array(dataset[y_variable]).reshape(-1,1)
print(z.shape)
print(w.shape)



(946, 1)
(946, 1)
(946, 1)
(946, 1)


In [6]:
#split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)


In [7]:
#build a model(simpleLinear)
Lin_reg = LinearRegression()

In [8]:
#training
model =  Lin_reg.fit(x_train, y_train)

# y_hat = Q_0 + Q_1 *x

In [9]:
Q_0 = model.intercept_
print(Q_0)
Q_1 = model.coef_
print(Q_1)


[9.92509731]
[[26.64504862]]


In [10]:
#result [rediction
#predict the result using whole dataset 
y_predict = model.predict(x_test)
print(y_predict)

[[327.00117587]
 [276.37558349]
 [193.77593278]
 [327.00117587]
 [268.38206891]
 [212.42746681]
 [255.0595446 ]
 [217.75647653]
 [212.42746681]
 [284.36909808]
 [231.07900084]
 [361.63973907]
 [231.07900084]
 [209.76296195]
 [350.98171963]
 [340.32370018]
 [209.76296195]
 [532.16805023]
 [247.06603001]
 [311.0141467 ]
 [263.05305919]
 [295.02711753]
 [143.1503404 ]
 [201.76944736]
 [273.71107863]
 [252.39503974]
 [313.67865156]
 [225.74999112]
 [337.65919532]
 [239.07251543]
 [268.38206891]
 [247.06603001]
 [185.78241819]
 [287.03360294]
 [135.15682582]
 [265.71756405]
 [265.71756405]
 [196.44043764]
 [220.4209814 ]
 [265.71756405]
 [239.07251543]
 [207.09845709]
 [215.09197167]
 [255.0595446 ]
 [334.99469046]
 [185.78241819]
 [281.70459322]
 [249.73053488]
 [281.70459322]
 [247.06603001]
 [209.76296195]
 [233.74350571]
 [247.06603001]
 [241.73702029]
 [249.73053488]
 [303.02063211]
 [196.44043764]
 [358.97523421]
 [169.79538902]
 [385.62028283]
 [217.75647653]
 [308.34964184]
 [220.42

In [11]:
#predict the single value
x_assum = np.array([15])
x_assum = x_assum.reshape(-1,1)

y_predict = model.predict(x_assum)
print(y_predict)

[[409.60082659]]


In [ ]:
#graph
plt.scatter(x_test, y_test, color = "Blue")
plt.plot(x_test, y_predict, color = "Red")
plt.show()

In [13]:
#Multiple Linear regression
#select the variables (x-FUELCONSUMPTION_HWY , y - CO2EMISSIONS)

x_variable1 = ['Engine Size(L)','Cylinders','Fuel Consumption(Hwy (L/100 km))' ] #input, Multiple input
y_variable1 = ['Fuel Consumption(Comb (L/100 km))'] #output

len(x_variable)
#reshape variable
x1 = dataset[x_variable1].values.reshape(-1,3) # 1st value is -1, next value is the length of x_variable
y1 = dataset[y_variable1].values.reshape(-1,1)
print(x1.shape)
print(y1.shape)
#(or)

(946, 3)
(946, 1)


In [14]:
x_train1, x_test1, y_train1, y_test1 =  train_test_split(x1, y1, test_size = 0.2) # 80% for train, 20% for testing
print(x_train1.shape)
print(x_test1.shape)

(756, 3)
(190, 3)


In [15]:
#build a model(multipleLinear)
Lin_reg1 = LinearRegression()

In [16]:
#training
model1 = Lin_reg.fit(x_train1, y_train1)

# y_hat = Q_0(intercept) + Q_1(slope) * FUELCONSUMPTION_HWY'+ Q_2*'ENGINESIZE'+ 

In [17]:
#finding intercept & slope(Coefficient)
Q_0 = model.intercept_
print(Q_0)
Q_1 = model.coef_
print(Q_1)
#just for understanding

[-0.18838622]
[[0.0984475  0.30125941 0.98817932]]


In [18]:
y_predict1 = model1.predict(x_test1)
print(y_predict1)

[[10.57074134]
 [12.39808392]
 [ 9.81994732]
 [11.99394183]
 [15.16498602]
 [15.00770354]
 [13.55399442]
 [ 7.49851508]
 [ 7.08859299]
 [ 8.52607341]
 [ 9.02016307]
 [11.26246687]
 [11.55892067]
 [10.27428755]
 [ 7.14262235]
 [ 7.04380442]
 [ 9.45481379]
 [14.77008473]
 [ 7.43907615]
 [12.39808392]
 [12.05301033]
 [ 9.118981  ]
 [ 8.03198374]
 [15.87603061]
 [ 6.98977506]
 [ 7.73552995]
 [ 7.68593576]
 [12.05301033]
 [ 7.34025822]
 [10.50243205]
 [ 7.24144029]
 [11.00576251]
 [11.51954167]
 [14.19612576]
 [14.89806647]
 [ 9.44496905]
 [ 9.21779893]
 [11.8951239 ]
 [13.52483061]
 [12.31858505]
 [ 9.06938682]
 [11.20339837]
 [ 7.98238956]
 [ 6.20366678]
 [ 8.8225272 ]
 [ 8.62489134]
 [ 9.21779893]
 [ 8.13080168]
 [11.50909296]
 [ 9.02016307]
 [15.29310468]
 [11.57861016]
 [14.50279474]
 [14.82915322]
 [ 7.53789408]
 [10.35401993]
 [14.22760879]
 [12.14137955]
 [10.13669457]
 [16.54880751]
 [11.75716049]
 [ 8.37322611]
 [14.09730783]
 [ 9.81994732]
 [10.80812664]
 [14.34453788]
 [10.65047

In [ ]:
#graph
plt.scatter(x_test1, y_test1, color = "Blue")
plt.plot(x_test1, y_predict1, color = "Red")
plt.show()

Task: 
1. Simple Linear -MSE, Absolute error, R^2
2. Repeat the same for Multiple IR
3. Graph for Multiple

In [20]:
#1. Simple Linear -MSE, Absolute error, R^2
mae = metrics.mean_absolute_error(y_test1, y_predict1)
mse = metrics.mean_squared_error(y_test1, y_predict1)
rmse = np.sqrt(mse) #mse**(0.5)  
r2 = metrics.r2_score(y_test1,y_predict1)

print("Results of sklearn.metrics:")
print("MAE:",mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-Squared:", r2)


Results of sklearn.metrics:
MAE: 0.40253799178180716
MSE: 0.2708959345254243
RMSE: 0.5204766416712899
R-Squared: 0.9597148491589794


In [ ]:
#regression 
#classification

1. Classification
2. Supervised learning
3. Predict the class or category of our target variable
4. Types : Binary Classification (0,1) - yes or no , Male=1, Female =0 
5. Multi-class classification;
Student name Age Year1 score Year2 Score
